### ISSUE TITLE
issue: nessus pukes on plugin updates when registering

### ISSUE THREAD

**Issue by sometheycallme** [cleanerbot/docker-nessus#20]
@jcwx @jumanjiman

When I use the data container, nessus fails downloading the plugins.   

```
CONTAINER ID        IMAGE                                 COMMAND                CREATED             STATUS          PORTS
              NAMES
f5290269ffae        sometheycallme/docker-nessus:latest   "/opt/nessus/sbin/ne   6 minutes ago       Exited (1) 21 seconds ago
              nessus-unlicensed
```

It fails at the same spot every time this plugin download is attempted.

![screenshot 2015-10-14 15 47 30](https://cloud.githubusercontent.com/assets/630113/10495666/faf3c88c-728a-11e5-8de1-7ee4c57d4239.png)

This does not occur when running nessus in a single self contained image.  (I'm wondering if this occurs only because of my crappy VM testing environment for docker right now)

**Comment by jcwx** [comment]
@sometheycallme 

There is enough space on the VM?  Just a thought.  The image ends up being just over 3 GB once the plugins are installed on the instances I've created.

I too have had the plugin download cause containers to exit such as you have.  The last one that did so I restarted and it completed the process.

**Comment by sometheycallme** [comment]
>There is enough space on the VM? 

Probably not.  I also noticed that loading the plugins takes about 3-5GB

**Comment by Passe12345** [comment]
Hi,

I'm experiencing the same problem here but I have enough space and I cannot restart the process. I have to say I tried to complete the process anyway, I tought it was OK with nessus registration and plugin download.

`docker ps -a --no-trunc=true
CONTAINER ID                                                       IMAGE                                 COMMAND                             CREATED             STATUS                      PORTS               NAMES
e08ab422ad91aa771ea7c6de82944cd537b7b297f7e98b7e8e32155f0803ad65   nessus:licensed                       "/opt/nessus/sbin/nessus-service"   41 minutes ago      Exited (1) 41 minutes ago                       nessus-licensed
5ea54a1eac8468d51de31ab311c8edfa40c80b0cb7dd79f6a5637c95a68d2de3   sometheycallme/docker-nessus:latest   "/opt/nessus/sbin/nessus-service"   4 hours ago         Exited (1) 3 minutes ago                        nessus-unlicensed
87c66e9e81c5ef50e943c6f9f4850ec6b603c1adbb9db796ec7d417214e6bb90   nessus-unlicensed-data:latest         "true"                              4 hours ago                                                         nessus-unlicensed-data`

` docker start -i 5ea54a1eac84
Error -- could not launch nessusd (No such file or directory)`

Why nessusd cannot be found ? I followed the docker cp process though.

`pwd
/home/passe/docks/docker-nessus/nessus-data/sbin
ll
total 16M
drwxr-xr-x 2 root  root  4.0K Oct 19 15:32 .
drwxr-xr-x 5 passe passe 4.0K Feb 22 13:55 ..
-rwxr-xr-x 1 root  root  4.2M Jul 20  2015 nessus-check-signature
-rwxr-xr-x 1 root  root  5.8M Jul 20  2015 nessuscli
-rwxr-xr-x 1 root  root  6.1M Jul 20  2015 nessusd
-rwxr-xr-x 1 root  root   11K Jul 20  2015 nessus-service`

Same issue with the supposedly "licensed" container: 
`docker run --name nessus-licensed2 -p 8834:8834 --mac-address 02:42:ac:11:00:01 --volumes-from nessus-unlicensed-data nessus
Unable to find image 'nessus:latest' locally
Pulling repository nessus
FATA[0008] Error: image library/nessus:latest not found
zsh: exit 1     docker run --name nessus-licensed2 -p 8834:8834 --mac-address  --volumes-from`

I noticed we have to specify nessus:licensed in order to run it (I suppose), but I have still the same error as before:
`docker run --name nessus-licensed2 -p 8834:8834 --mac-address 02:42:ac:11:00:01 --volumes-from nessus-unlicensed-data nessus:licensed
Error -- could not launch nessusd (No such file or directory)`

Anyway, the procedure is not working for me and I strictly followed it. Any clue about that behavior ?

**Comment by sometheycallme** [comment]
@Passe12345 

Thanks for trying the procedure out.

Allow me to look at the process once more.   I know that @jcwx has had much more luck in getting the data into the container (pretty sure we tar'd up the directory to present later on in the container runtime).

**Comment by Passe12345** [comment]
Interesting, can anyone of you describe how to include all the data into the container then ?

To complete, here is the list of images I have:
```
docker images
REPOSITORY                     TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
nessus                         licensed            7395be6cb7b3        About an hour ago   837.7 MB
nessus-unlicensed-data         latest              2363db01e419        4 hours ago         67.31 MB
sometheycallme/docker-nessus   latest              f83a7053a9ad        4 months ago        302.3 MB
```

**Comment by jcwx** [comment]
I wrote things up in a way I hope is understandable here, which includes systemd based services their associated timers.  Instructions for the backup stuff is in there.

https://github.com/jcwx/docker-nessus

**Comment by sometheycallme** [comment]
@jcwx - when you created your docker-nessus did you go through the registration and pull in the latest (eg scratch build) or did you copy over an already running Nessus with the plugins?

**Comment by jcwx** [comment]
I copied the backup I'd created into the install, so it was using the previous license/config.  It's possible to start from scratch by commenting out the backup restore items in the Dockerfile, however.

**Comment by Passe12345** [comment]
Apparently when I launch with the option "--volumes-from nessus-unlicensed-data" several files are missing. This is not the case when I avoid this volume.

```
docker run -t -i --name nessus-licensed4 -p 8834:8834 --mac-address 02:42:ac:11:00:01 --entrypoint bash --volumes-from nessus-unlicensed-data nessus:licensed
[root@12d9802e326b /]# cd /opt/nessus/sbin/
[root@12d9802e326b sbin]# ls
nessus-check-signature  nessus-service
[root@12d9802e326b sbin]# ls -lash
total 4.2M
4.0K drwxr-xr-x  2 root root 4.0K Feb 22 16:14 .
4.0K drwxr-xr-x 10 root root 4.0K Feb 22 16:14 ..
4.2M -rwxr-xr-x  1 root root 4.2M Jul 20  2015 nessus-check-signature
 12K -rwxr-xr-x  1 root root  11K Jul 20  2015 nessus-service
```

Without the nessus-unlicensed-data volume:
```
docker run -t -i --name nessus-licensed3 -p 8834:8834 --mac-address 02:42:ac:11:00:01 --entrypoint bash nessus:licensed
[root@4b28f9e3d136 /]# ls -lah /opt/nessus/sbin/
total 16M
drwxr-xr-x  2 root root 4.0K Oct 19 13:32 .
drwxr-xr-x 12 root root 4.0K Feb 23 11:57 ..
-rwxr-xr-x  1 root root 4.2M Jul 20  2015 nessus-check-signature
-rwxr-xr-x  1 root root  11K Jul 20  2015 nessus-service
-rwxr-xr-x  1 root root 5.8M Jul 20  2015 nessuscli
-rwxr-xr-x  1 root root 6.1M Jul 20  2015 nessusd
```

This explains why nessusd is not found in my previous post. However, the license is not correctly setup in this docker instance. As I installed it from scratch I have no backup of it.

@jcwx your solution is interesting, but I won't use it since it requires a systemd based system, this is not my case and I don't want to spend much time to make it compliant to my system.

**Comment by sometheycallme** [comment]
@Passe12345 

It appears as though you are getting stuck at the last step I have gotten to in the procedure.  Step 5, adding the license.   There is a middle step after step 5, which is the automatic updates that Nessus tries (plugins) after successfully registering (registering works fine - I've tested it).

I think a good next step would be to try registering offline, and requesting to download the plugins in a tarball that can be added to the ```nessus-licensed-data``` container.   When time permits I will try this and update the thread.


If successful, we move to step 6

```
docker ps
docker stop <container ID>
docker ps -a
docker commit <container ID> <image-name>
docker images
```

The challenge with Nessus is that the plugins are dynamically updated every 24 hours, so once we have a running data container - it needs to be saved periodically (scheduled job).

The idea with this image was to decouple the nessusd from the nessus-data (license, plugins, scans)

**Comment by sometheycallme** [comment]
Goal:  Create a newly licensed container, without any historical reference to an organizations existing Nessus Setup. (fresh, brandy new install)

Here are a few links to the process to register offline.

http://static.tenable.com/documentation/nessus_v6_command_line_reference.pdf

https://plugins.nessus.org/offline.php

<img width="1139" alt="screenshot 2016-02-23 09 24 21" src="https://cloud.githubusercontent.com/assets/630113/13254665/54667cc4-da10-11e5-90af-f92351ca16b2.png">
<img width="815" alt="screenshot 2016-02-23 09 30 13" src="https://cloud.githubusercontent.com/assets/630113/13254664/5452cb7a-da10-11e5-8dcc-26c18b5dfbb1.png">
<img width="1124" alt="screenshot 2016-02-23 09 30 23" src="https://cloud.githubusercontent.com/assets/630113/13254667/546ef61a-da10-11e5-93e8-73c61a0b5c5c.png">
<img width="1103" alt="screenshot 2016-02-23 09 31 04" src="https://cloud.githubusercontent.com/assets/630113/13254668/546f718a-da10-11e5-8268-c25605e7ab6c.png">

**Comment by sometheycallme** [comment]
>Apparently when I launch with the option "--volumes-from nessus-unlicensed-data" 

Yes, that is correct.  when getting to step 5 - we want to commit the registered data to the volume and create a more permanent data volume.

Another option is to NOT create a data volume and just register Nessus as is (as you mention) without using a separate container.   This way everything is self contained.   

Either way - I think that the plugins are the real challenge here.

**Comment by Passe12345** [comment]
@sometheycallme I just saw your answers. In the meantime I managed to solve completely the issue by copying "nessuscli  nessusd" binaries from "nessus-licensed3" into "nessus-licensed4" container. By now, my "nessus-licensed4" container works perfectly with the previously registered license.

I believe you forgot to specify those two binaries when creating the "nessus-unlicensed-data" image.

**Comment by sometheycallme** [comment]
>container works perfectly with the previously registered license.

Plugins included?

**Comment by Passe12345** [comment]
Everything seems fine yes.

```
[root@12d9802e326b sbin]# ./nessuscli update

----- Fetching the newest updates from nessus.org -----

Nessus Plugins: Complete

Nessus Core Components: Complete

 * Nessus Plugins are now up-to-date and the changes will be automatically processed by Nessus.
 * Nessus Core Components are now up-to-date and the changes will be automatically processed by Nessus.
```

**Comment by sometheycallme** [comment]
@Passe12345 

Your help here is appreciated.  we should update our procedures to include steps you took to get this working.

**Comment by sometheycallme** [comment]
Do you mean this?  Because at that point we might as well just do /opt/nessus :) 

```
COPY var /opt/nessus/var
COPY etc /opt/nessus/etc
COPY sbin /opt/nessus/sbin
COPY cli /opt/nessus/cli
COPY nessusd /opt/nessus/nessusd

# use that data as a volume for startup
VOLUME /opt/nessus/var
VOLUME /opt/nessus/etc
VOLUME /opt/nessus/sbin
VOLUME /opt/nessus/cli
VOLUME /opt/nessus/nessusd

**Comment by Passe12345** [comment]
Yes, but it is needed to investigate why nessusd and nessuscli are not present in the volume after the first plugin download. Maybe, during the plugin download phase a Nessus core update is also performed ? It is maybe something related to that, just a guess.

**Comment by sometheycallme** [comment]
>Maybe, during the plugin download phase a Nessus core update is also performed ?

I have a hunch that because (as you pointed out) nessus/cli is missing, the plugins don't work because Nessus is looking for the cli commands via GUI.

**Comment by Passe12345** [comment]
Another point, I tried to save / load (on a new physical machine) the 2 volumes after committing the 2 modified images.
Nessus and plugins are loading but the license is invalid, even when using the same MAC address. It is not possible to use it on several environments.

**Comment by sometheycallme** [comment]
Thanks @Passe12345 

Are you running 6.4.3 as placed into this repo?  or did you register and download?

**Comment by Passe12345** [comment]
As you could notice, yes I use the version 6.4.3 of nessud and nessuscli which I imported from another container.

**Comment by stackpivot** [comment]
Any news on this? I have the same problem

**Comment by sometheycallme** [comment]
Hey guys.  Sorry for delaying a reply here.  Been busy!

@seccubus added a PR with make file that handles licensing Nessus containers nicely.  If I remember correctly, Nessus needs a static MAC address

cc @jcwx 

https://github.com/cleanerbot/docker-nessus/blob/master/Makefile

**Comment by sometheycallme** [comment]
WRT to the plugins updating, I haven't tested.

**Comment by sometheycallme** [comment]
#26

**Comment by sometheycallme** [comment]
#32
